# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install system dependencies - Comprehensive
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl-dev \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libxxf86vm-dev \
          libxinerama-dev \
          libxft-dev \
          mesa-common-dev \
          libglu1-mesa-dev

    - name: Set PKG_CONFIG_PATH
      run: |
        echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
